# Change these first
owner: TTRCharlie # Your GitHub organization or username, where this repository lives
repo: Charlie-Cloud-Status # The name of this repository

sites:
  - name: EG-SMP phpmyadmin
    url: https://pma.egsmp.eu  
  - name: Charlie Cloud Git
    url: https://git.charlie-cloud.hu
  - name: https://ip.charlie-cloud.hu
    url: https://ip.charlie-cloud.hu
  - name: Charlie Cloud Storage
    url: $CLOUD_STORAGE

assignees: # Users to assign downtime issues (optional)
  - TTRCharlie
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.charlie-cloud.hu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Charlie Cloud Status
  introTitle: "Charlie Cloud Status"
  introMessage: "This is the Charlie Cloud Site uptime status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TTRCharlie/Charlie-Cloud-Status.git
    - title: Server uptime
      href: https://uptime.charlie-cloud.hu
  metaTags:
    - name: "robots"
      content: "noindex"
  theme: night

status-page:
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
